// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktbbkwohgpsqrihouxgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0YmJrd29oZ3BzcXJpaG91eGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzAyODAsImV4cCI6MjA2NTMwNjI4MH0.p2US0LcGAbc1t-c1wtKLLNT_tOyfbj8i9cl9bl8qpwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);